[package]
name = "foton"
version = "0.1.0"
edition = "2021"
description = "Lightspeed photo management tool"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
